= Acknowledgements & Citations


== Funding acknowledgements

The NHGRI-EBI GWAS Catalog is funded in part by http://projectreporter.nih.gov/project_info_description.cfm?aid=8739756&icde=23818978[NHGRI Grant Number 1U41HG007823-01] and BBSRC Grant Number BB/M013146/1, and delivered by collaboration between the NHGRI, EMBL-EBI and NCBI.


== Citing the GWAS Catalog

===  How to cite NHGRI-EBI GWAS Catalog data:

_Burdett T (EBI), Hall PN (NHGRI), Hastings E (EBI), Hindorff LA (NHGRI), Junkins HA (NHGRI), Klemm AK (NHGRI), MacArthur J (EBI), Manolio TA (NHGRI), Morales J (EBI), Parkinson H (EBI) and Welter D (EBI)._ +
The NHGRI-EBI Catalog of published genome-wide association studies. +
Available at: www.ebi.ac.uk/gwas. Accessed [date of access], version [version number]. +
_version number only applies to the download spreadsheet - v1.0 for the traditional version of the spreadsheet, v1.0.1 for the version with added EFO terms_  +

=== How to cite the NHGRI-EBI GWAS Catalog:

_Welter D, MacArthur J, Morales J, Burdett T, Hall P, Junkins H, Klemm A, Flicek P, Manolio T, Hindorff L, and Parkinson H._ +
The NHGRI GWAS Catalog, a curated resource of SNP-trait associations. +
Nucleic Acids Research, 2014, Vol. 42 (Database issue): D1001-D1006. +


== Licensing information

The NHGRI-EBI GWAS Catalog and all its contents are available under the general http://www.ebi.ac.uk/about/terms-of-use[Terms of Use for EMBL-EBI Services].

All code for the GWAS Catalog infrastructure can be found in https://github.com/EBISPOT/goci[our Github repository]. The code is freely available under http://www.apache.org/licenses/LICENSE-2.0[the Apache version 2.0 license]


== Publications

_Welter D, MacArthur J, Morales J, Burdett T, Hall P, Junkins H, Klemm A, Flicek P, Manolio T, Hindorff L, and Parkinson H._ +
http://nar.oxfordjournals.org/content/42/D1/D1001.full[The NHGRI GWAS Catalog, a curated resource of SNP-trait associations.] +
Nucleic Acids Research, 2014, Vol. 42 (Database issue): D1001-D1006. +

_Hindorff LA, Sethupathy P, Junkins HA, Ramos EM, Mehta JP, Collins FS and Manolio TA._ +
http://www.genome.gov/Pages/About/OD/NewsAndFeatures/PNASGWASOnlineCatalog.pdf[Potential etiologic and functional implications of genome-wide association loci for human diseases and traits.] +
Proc. Natl Acad. Sci. USA, 2009, 106, 9362–9367 +



== Credits &amp; acknowledgements

* Font generated by http://www.flaticon.com[flaticon.com] under http://creativecommons.org/licenses/by/3.0/[CC BY license].
The authors are http://picol.org[Picol].

* http://www.jetbrains.com/idea/index.html[IntelliJ IDEA]: Full-featured commercial IDE with a complete set of tools and integrations with the most important modern technologies and frameworks, such as Spring and Hibernate — a must-have for effective Web and Java EE development.

